spring:
  application:
    name: producerService

server:
  port: 9091

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
